# Generated by Django 2.2 on 2021-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsd_trips', '0006_django_2_20191106'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(default='svg/logo-scuba-white-trimmed.svg', upload_to='trim_images/', verbose_name='Trip Image'),
        ),
    ]
